apiVersion: apps/v1
kind: Deployment
metadata:
  name: met-backend
  namespace: met
spec:
  replicas: 3
  selector:
    matchLabels:
      app: met-backend
  template:
    metadata:
      labels:
        app: met-backend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: met-backend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: backend
          image: met/backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: met-secrets          # Ver infrastructure/k8s/secrets.yaml
            - configMapRef:
                name: met-backend-config   # Ver infrastructure/k8s/backend-configmap.yaml
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: "500m"
              memory: "768Mi"
            limits:
              cpu: "2"
              memory: "1536Mi"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: met-backend
  namespace: met
spec:
  selector:
    app: met-backend
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
