apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: met-ingress
  namespace: met
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: api.met.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: met-backend
                port:
                  number: 80
    - host: met.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-comercial
                port:
                  number: 80
    - host: admin.met.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-admin
                port:
                  number: 80
  tls:
    - hosts:
        - api.met.com
        - met.com
        - admin.met.com
      secretName: met-tls-secret
